### ISSUE TITLE
Allow syncing from fileset

### ISSUE THREAD

**Issue by martinklepsch** [hashobject/boot-s3#4]
The task currently syncs from target dir so when I do something like `boot build deploy` the syncing to `target/` is done after the deploy task and there's no difference. Only a second invocation of the sync task will actually pickup the changes.

**Comment by podviaznikov** [comment]
valid bug, noticed that as well

**Comment by bhagany** [comment]
I think this bug is fixed as of https://github.com/hashobject/boot-s3/commit/8ef5a48ae2d52ff983d01ef8944394686503f85b.

**Comment by kenbier** [comment]
@podviaznikov Nice to see this is fixed! Can you cut a non-snapshot release with all the latest changes?

**Comment by bhagany** [comment]
+1 from me - it would also be helpful to me to see https://github.com/hashobject/boot-s3/pull/8 in the next release, if it still meets with your approval

**Comment by kenbier** [comment]
@bhagany we opened a fork and push a release to clojars with #8 merged: 

https://github.com/AdStage/boot-s3

**Comment by bostonaholic** [comment]
How would I sync from the target directory? I would prefer to just have `boot deploy` which syncs from `target/` so I can split the jobs on CI and not have to rerun `build` before every `deploy`.

**Comment by kenbier** [comment]
@bostonaholic Its been awhile since I worked on a project that used this library, but I remember `boot-clj` not taking the target directory as an input. So if you want to build in one step and sync in another, the output of the build step should write the assets into a directory that is an input to the sync task. 

See the docs [here](https://github.com/boot-clj/boot/wiki/Tasks#boot-task-model) for more info on the boot filesystem. 

This library looks in the boot [output filesystem](https://github.com/boot-clj/boot/blob/master/doc/boot.core.md#output-files) for the assets.

**Comment by bostonaholic** [comment]
Thanks for the tip @kenbier. I just decided to do `(set-env! :resource-paths #{"target"})` like so:

```clojure
(deftask build
  "Build distribution."
  []
  (comp
   (cljs :optimizations :advanced
         :source-map true)
   (sift :include #{#".boot-env"}
         :invert true)
   (target)))

(deftask deploy
  "Deploy distribution."
  []
  (set-env! :resource-paths #{"target"})
  (s3-sync :source "" ; target/
           :bucket (env :aws-bucket)
           :access-key (env :aws-access-key)
           :secret-key (env :aws-secret-key)
           :force true))
```

**Comment by kenbier** [comment]
@bostonaholic ah clever! Thats an even a better approach. 

Deleting my suggestion cause people should do that! :)

**Comment by bostonaholic** [comment]
@martinklepsch I think this issues can be marked as "Closed".

**Comment by martinklepsch** [comment]
👍 

For people needing something a little more flexible: I also ended up writing my own S3 sync task for boot as part of *Confetti*, a toolchain to publish static sites. It supports selective syncing and metadata. Task docs can be read via `boot -d confetti sync-bucket -h` or [here](https://github.com/confetti-clj/confetti#syncing-your-site).
